- name: PB1
  hosts: localhost
  vars:
    pg_version: "17"

  tasks:

    - name: PB1 TASK1
      ansible.builtin.debug:
        msg: "Hello World!"


    - name: PB1 TASK2
      ansible.builtin.debug:
        msg: "{{ANSIBLE_MY_TEXT}}"
