---
- name: Test2
  hosts: all
  gather_facts: no

  tasks:
  - name: Run shell 
    ansible.builtin.shell: echo `hostname`
    register: command_output
      
  - name: Create your local file on master node
    ansible.builtin.file:
      path: output.txt
      owner: jenkins
      group: jenkins
      mode: '0644'
    delegate_to: localhost
    
  - name: Print output to file
    ansible.builtin.copy:
      content: "{{command_output.stdout}}"
      dest: output.txt
    delegate_to: localhost      
    

