---
- name: Test2
  hosts: all
  gather_facts: no

  tasks:
  - name: Run shell 
    ansible.builtin.shell: echo `hostname`
    register: command_output

  - name: Remove your local file on master node
    ansible.builtin.file:
      path: /tmp/output.txt
      state: absent
    delegate_to: localhost

  - name: Create your local file on master node
    ansible.builtin.file:
      path: /tmp/output.txt
      state: touch
    delegate_to: localhost

      
  - name: Create your local file on master node
    ansible.builtin.lineinfile:
      path: /tmp/output.txt
      line: "{{ inventory_hostname }} {{ command_output.stdout_lines }} {{ command_output.stdout_lines }}"
    delegate_to: localhost
    
    

