---
- name: Test2
  hosts: all
  gather_facts: no

  tasks:
  - name: Run shell 
    ansible.builtin.shell: echo `hostname`
    register: command_output
    
  - name: Print shell
    ansible.builtin.debug: 
      msg: command_output
    

