---
- name: Test2
  hosts: all
  gather_facts: no

  tasks:
  - name: Run shell 
    ansible.builtin.shell: echo `hostname`
    register: command_output
      
  - name: Create your local file on master node
    ansible.builtin.lineinfile:
      path: /tmp/output.txt
      line: "{{ command_output.stdout_lines }}"
      create: yes
    delegate_to: localhost
    
    

